apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          imagePullPolicy: '{{ .Values.image.pullPolicy }}'
          volumeMounts:
            - name: mongodb-db
              mountPath: '{{ .Values.persistence.db.mountPath }}'
            - name: mongodb-configdb
              mountPath: '{{ .Values.persistence.configdb.mountPath }}'
      volumes:
        - name: mongodb-db
          persistentVolumeClaim:
            claimName: mongodb-db
        - name: mongodb-configdb
          persistentVolumeClaim:
            claimName: mongodb-configdb
