---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-db
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '{{ .Values.persistence.db.storageSize }}'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-configdb
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '{{ .Values.persistence.configdb.storageSize }}'
