---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '{{ .Values.persistence.db.storageSize }}'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-configdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '{{ .Values.persistence.configdb.storageSize }}'
