repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        exclude: '.*/templates/.*[.]ya?ml'
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        exclude: '.*/templates/.*[.]ya?ml'
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        files: 'Tiltfile'
        types_or: ['file']
