image:
  repository: mongo
  tag: 6.0
  pullPolicy: IfNotPresent

persistence:
  # Must match the VOLUME declataion in the container image
  # See `docker history --no-trunc mongo:6.0`
  db:
    enabled: true
    mountPath: /data/db
    storageSize: 1Gi
  configdb:
    enabled: true
    mountPath: /data/configdb
    storageSize: 10Mi

service:
  type: ClusterIP
  port: 27017
