image:
  repository: floppies
  tag: dev
  pullPolicy: Never

service:
  type: ClusterIP
  port: 3000

mongodb:
  namespace: data-store
  serviceName: mongodb

minio:
  namespace: data-store
  serviceName: minio
